import faker from "@faker-js/faker";
import uuid from "react-uuid";

const seed = () => {
  return [
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
    { name: faker.name.firstName(), id: uuid(), url: faker.image.avatar() },
  ];
};

export default seed;
